language: python
python:
- '3.5'
cache: pip
services:
- postgresql
install: python setup.py install
script: python setup.py nosetests
notifications:
  slack: oblong-antelope:1eXsnKpfCiWpdAGGizILVk7j
addons:
  ssh_known_hosts: battle.horse
before_deploy:
- openssl aes-256-cbc -K $encrypted_4e1d568d3b8a_key -iv $encrypted_4e1d568d3b8a_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh travis-ci@battle.horse 'cd /var/www/oblong && git pull && touch oblong.wsgi'
  on:
    branch: master
