language: python
python:
  - "3.5"

cache: pip

services:
  - postgresql

install: "python setup.py install"
script: "python setup.py nosetests"

notifications:
  slack: oblong-antelope:1eXsnKpfCiWpdAGGizILVk7j
